
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[134] =
    {   0,
       33,   33,   39,   39,   36,   36,   54,   54,   51,   51,
       59,   57,   58,   56,   57,   58,   56,   58,   57,   58,
       57,   58,   18,   57,   58,   57,   58,   33,   58,   58,
       58,   43,   58,   58,   58,   58,   58,   58,   45,   58,
       58,   39,   58,   41,   58,   40,   58,   36,   58,   38,
       58,   37,   58,   47,   58,   58,   58,   58,   58,   49,
       58,   58,   48,   58,   54,   58,   58,   51,   58,   58,
       19,   33,   34,   42,   44,   39,   36,   48,   54,   55,
       51,   52,   35,   53,   32,   50,    7,   17,   20,   46,
       15,    8,    9,   16,    4,    5,   21,16415,   13,   14,

        6,    3,16411,   12,16412,16408, 8219,    1, 8220, 8216,
     8215,16407, 8219,   10,    2, 8220, 8215,   11,16414,16406,
     8222, 8214, 8223,16413, 8222, 8221, 8221,16409, 8217, 8217,
    16410, 8218, 8218
    } ;

static const flex_int16_t yy_accept[401] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    3,    3,    4,
        5,    6,    7,    7,    7,    7,    7,    8,    9,   10,
       11,   12,   14,   17,   19,   21,   23,   26,   28,   30,
       31,   32,   34,   35,   36,   37,   38,   39,   41,   42,
       44,   46,   48,   50,   52,   54,   56,   57,   58,   59,
       60,   62,   63,   65,   67,   68,   70,   71,   72,   72,
       72,   72,   72,   72,   73,   73,   74,   75,   75,   75,
       75,   75,   76,   76,   77,   78,   78,   78,   78,   78,
       78,   79,   80,   80,   81,   82,   82,   83,   83,   83,
       83,   83,   83,   84,   84,   84,   84,   84,   84,   84,

       84,   84,   84,   85,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   88,   88,   88,   88,   89,   89,   89,   89,
       89,   90,   90,   90,   90,   90,   90,   90,   90,   91,

       91,   92,   92,   92,   92,   93,   93,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   95,   95,   95,   95,   95,   96,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   98,   98,   98,
       98,   99,   99,   99,  100,  101,  101,  101,  102,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  104,  105,  105,  105,
      105,  105,  105,  105,  106,  106,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  108,  108,  108,  109,
      109,  109,  109,  110,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  113,  113,  113,  113,  113,  114,  115,
      115,  116,  116,  116,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  118,  118,  118,  118,  118,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  120,  120,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  122,  123,  123,  123,  123,  123,  123,  123,  124,
      124,  124,  124,  125,  126,  126,  126,  126,  126,  126,
      126,  126,  127,  127,  127,  127,  127,  127,  127,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  129,
      129,  130,  130,  130,  131,  131,  132,  133,  134,  134

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    6,    1,    1,
        1,    6,    1,    1,    7,    1,    8,    9,   10,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,   13,
       14,   15,    6,    1,   16,   17,   18,   19,   20,   21,
        1,   22,   23,    1,    1,    1,   24,   25,    1,   26,
        1,   27,   28,   29,    1,    1,   30,    1,    1,    1,
        6,    6,    6,    1,    1,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,
       44,   45,    1,   46,   47,   48,   49,    1,   50,   51,
       52,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    1,    1,    2,    2,    1,    2,    1,    1,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[414] =
    {   0,
        0,    3,  612,  611,   12,   15,   18,   21,   49,   59,
       68,   77,   74,   79,   37,   43,  100,  109,  610,  609,
      615,  620,  620,  620,  599,   84,  620,  566,  605,  604,
      620,  620,  605,  578,  562,  576,  560,  620,  114,    0,
      620,  620,    0,  620,  620,  620,  561,  573,  554,  554,
      620,  124,  620,    0,    6,  594,  593,  620,   98,  592,
      107,  551,  585,  589,  588,  579,  620,  552,  543,  550,
      541,  620,  123,    0,    0,  545,  540,  545,  540,  127,
      620,    0,  578,  620,  577,  576,  567,  574,  133,  533,
      567,  162,  620,  531,  542,  529,  540,  533,  538,  540,

      532,  563,  620,  620,  557,  119,  537,  516,    3,  547,
      530,  533,  517,  514,  509,  521,  524,  553,  522,  521,
      526,  519,  510,  620,  123,   24,  521,  507,  502,  518,
      504,  499,  501,  506,  510,  141,  497,  500,  497,  488,
      494,  504,  506,  497,  489,  497,  498,  488,  483,  499,
      485,  487,  486,  478,  475,  472,  491,  476,  490,  489,
      482,  484,  154,   32,  480,  481,  467,  473,  478,  464,
      468,  468,  504,  467,  457,  454,  473,  458,  462,  453,
      470,  620,  459,  458,  458,  620,  454,  458,  460,   92,
      620,  459,  156,  458,  457,  158,  453,  455,  620,  448,

      620,  447,  446,  446,  620,  443,  620,  449,  448,   71,
      448,  433,  437,   11,  160,  162,  446,  455,  175,  191,
      195,  620,  442,  441,  163,  432,  427,  620,  429,  434,
      436,  197,  199,  437,  425,  201,  620,  420,  448,  212,
      199,  205,  218,  419,  620,  421,  426,  620,  620,  419,
      427,  427,  223,  226,  230,  233,  414,  409,  423,  237,
      413,  425,  406,  406,  240,   59,  620,  409,  417,  411,
      415,   48,  244,   67,  250,  247,  405,  405,  413,  256,
      258,  402,  397,  402,  397,  255,  402,  406,  620,  392,
      395,  394,  262,  620,  406,  390,  404,  388,  386,  272,

      275,  277,    0,  391,  396,  398,  390,  281,  620,  380,
      620,  386,  376,  287,  384,  375,  382,  373,  374,  285,
      298,  291,  304,    0,  385,  390,  383,  374,  620,  338,
      365,  331,  341,  318,  326,  308,  310,  165,  314,  311,
      327,  315,  281,  281,  272,  264,  269,  267,  321,  323,
      320,  620,  250,  223,  236,  216,  211,  208,  620,  205,
      192,  331,  274,  328,  193,  181,  181,  163,  170,  165,
      136,  332,  126,  136,  122,  131,   96,   72,  335,   81,
       76,    7,  346,   10,  348,  350,    1,  361,  346,  365,
      360,  370,  372,  371,  383,  379,  382,  385,  620,  396,

      398,  400,  402,  404,  406,  408,  410,  412,    8,    6,
        3,  414,    0
    } ;

static const flex_int16_t yy_def[414] =
    {   0,
      400,  400,  401,  401,  402,  402,  402,  402,  403,  403,
      404,  404,  402,  402,  405,  405,  406,  406,  407,  407,
      399,  399,  399,  399,  399,  399,  399,  399,  408,  408,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  409,
      399,  399,  410,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  411,  399,  412,  412,  399,  399,  399,
      399,  399,  399,  408,  408,  399,  399,  399,  399,  399,
      399,  399,  399,  409,  410,  399,  399,  399,  399,  399,
      399,  411,  399,  399,  412,  412,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  413,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  413,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,    0,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399
    } ;

static const flex_int16_t yy_nxt[673] =
    {   0,
      324,   23,   24,   82,   23,   24,   75,   25,   74,   83,
       25,  399,   26,   84,   27,   26,   32,   27,  399,   32,
       33,   33,   38,   33,   33,   38,  234,   39,   39,  235,
       39,   39,   34,  190,  190,   34,  191,  134,   52,   52,
       35,  135,  399,   35,   52,   52,   28,   36,  390,   28,
       36,   53,  387,   41,   42,  384,   42,   53,  152,   37,
       42,   42,   37,   41,   42,  291,   42,  153,  286,  286,
       42,   42,   44,   45,  292,   45,  293,  293,   46,   45,
       45,   44,   45,   46,   45,   59,   59,   60,   45,   45,
       47,   61,   48,  190,  190,   47,  191,   48,   49,   59,

       59,   50,  229,   49,   31,   31,   50,   31,   89,   89,
      352,   31,   55,   31,   31,  352,   31,  230,   72,  383,
       31,   55,   73,   73,   73,   80,   80,   72,   80,   80,
       62,   73,   73,   73,   89,   89,  126,  127,   81,  382,
      147,   81,  163,  163,   62,  128,  129,  130,  131,  148,
      149,  150,  151,   90,  164,  163,  163,  215,  215,  219,
      219,  215,  215,  236,  236,  352,  237,  164,  381,  216,
      352,  220,  380,  216,  351,  351,  219,  219,  378,   90,
      107,  108,  377,  109,  110,  111,  112,  113,  220,  114,
      115,  116,  240,  240,  246,  241,  242,  242,  253,  253,

      255,  255,  236,  236,  359,  237,  242,  242,  243,  247,
      254,  376,  256,  240,  240,  261,  241,  262,  243,  265,
      265,  375,  266,  263,  253,  253,  264,  273,  273,  374,
      274,  255,  255,  373,  275,  275,  254,  276,  280,  280,
      371,  265,  265,  256,  266,  273,  273,  370,  274,  369,
      281,  275,  275,  359,  276,  294,  294,  280,  280,  302,
      302,  368,  303,  308,  308,  308,  367,  295,  366,  281,
      314,  314,  314,  320,  320,  296,  322,  322,  302,  302,
      365,  303,  297,  372,  372,  321,  320,  320,  323,  308,
      308,  308,  322,  322,  298,  314,  314,  314,  321,  337,

      337,  294,  338,  294,  323,  339,  339,  361,  340,  349,
      349,  337,  337,  360,  338,  339,  339,  359,  340,  352,
      352,  350,  349,  349,  362,  362,  359,  363,  364,  364,
      364,  353,  362,  362,  350,  363,  364,  364,  364,  354,
      379,  379,  379,  379,  379,  379,  355,  385,  385,  385,
      385,  388,  388,  358,  389,  391,  391,  357,  356,  386,
      294,  386,  388,  388,  348,  389,  392,  392,  394,  394,
      394,  392,  392,  395,  395,  294,  396,  347,  393,  394,
      394,  394,  346,  393,  395,  395,  345,  396,  397,  397,
      398,  398,  398,  398,  398,  398,   22,   22,   29,   29,

       31,   31,   40,   40,   43,   43,   51,   51,   54,   54,
       56,   56,   64,   64,   85,   85,  344,  343,  342,  341,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  319,  318,  317,  316,  315,  313,  312,  311,
      310,  309,  307,  306,  305,  304,  301,  300,  299,  290,
      289,  288,  287,  285,  284,  283,  282,  279,  278,  277,
      272,  271,  270,  269,  268,  267,  260,  259,  258,  257,
      252,  251,  250,  249,  248,  245,  244,  239,  238,  233,
      232,  231,  228,  227,  226,  225,  224,  223,  222,  173,
      221,  218,  217,  214,  213,  212,  211,  210,  209,  208,

      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      173,  197,  196,  195,  194,  193,  192,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  146,  145,  144,  143,  118,   67,  118,  142,
      141,  140,  139,  138,  137,  136,  133,  132,  125,  124,
      123,  122,  121,  120,  118,  119,  118,  117,  106,  105,
      104,  103,  399,   86,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,  399,   65,   92,   91,   88,   87,

       86,   79,   78,   77,   76,   71,   70,   69,   68,   67,
       66,   65,   63,   58,  399,   57,   57,   30,   30,   21,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399
    } ;

static const flex_int16_t yy_chk[673] =
    {   0,
      413,    1,    1,  411,    2,    2,  410,    1,  409,   55,
        2,    0,    1,   55,    1,    2,    5,    2,    0,    6,
        5,    5,    7,    6,    6,    8,  214,    7,    7,  214,
        8,    8,    5,  164,  164,    6,  164,  109,   15,   15,
        5,  109,    0,    6,   16,   16,    1,    5,  387,    2,
        6,   15,  384,    9,    9,  382,    9,   16,  126,    5,
        9,    9,    6,   10,   10,  272,   10,  126,  266,  266,
       10,   10,   11,   11,  272,   11,  274,  274,   13,   11,
       11,   12,   12,   14,   12,   26,   26,   26,   12,   12,
       13,   26,   13,  190,  190,   14,  190,   14,   13,   59,

       59,   13,  210,   14,   17,   17,   14,   17,   61,   61,
      381,   17,   17,   18,   18,  380,   18,  210,   39,  378,
       18,   18,   39,   39,   39,   52,   52,   73,   80,   80,
       26,   73,   73,   73,   89,   89,  106,  106,   52,  377,
      125,   80,  136,  136,   59,  106,  106,  106,  106,  125,
      125,  125,  125,   61,  136,  163,  163,  193,  193,  196,
      196,  215,  215,  216,  216,  376,  216,  163,  375,  193,
      374,  196,  373,  215,  338,  338,  219,  219,  371,   89,
       92,   92,  370,   92,   92,   92,   92,   92,  219,   92,
       92,   92,  220,  220,  225,  220,  221,  221,  232,  232,

      233,  233,  236,  236,  369,  236,  242,  242,  221,  225,
      232,  368,  233,  240,  240,  241,  240,  241,  242,  243,
      243,  367,  243,  241,  253,  253,  241,  254,  254,  366,
      254,  255,  255,  365,  256,  256,  253,  256,  260,  260,
      361,  265,  265,  255,  265,  273,  273,  360,  273,  358,
      260,  275,  275,  357,  275,  276,  276,  280,  280,  281,
      281,  356,  281,  286,  286,  286,  355,  276,  354,  280,
      293,  293,  293,  300,  300,  276,  301,  301,  302,  302,
      353,  302,  276,  363,  363,  300,  320,  320,  301,  308,
      308,  308,  322,  322,  276,  314,  314,  314,  320,  321,

      321,  348,  321,  347,  322,  323,  323,  346,  323,  336,
      336,  337,  337,  345,  337,  339,  339,  344,  339,  340,
      340,  336,  349,  349,  350,  350,  343,  350,  351,  351,
      351,  340,  362,  362,  349,  362,  364,  364,  364,  340,
      372,  372,  372,  379,  379,  379,  340,  383,  383,  385,
      385,  386,  386,  342,  386,  389,  389,  341,  340,  383,
      335,  385,  388,  388,  334,  388,  390,  390,  391,  391,
      391,  392,  392,  393,  393,  333,  393,  332,  390,  394,
      394,  394,  331,  392,  395,  395,  330,  395,  396,  396,
      397,  397,  397,  398,  398,  398,  400,  400,  401,  401,

      402,  402,  403,  403,  404,  404,  405,  405,  406,  406,
      407,  407,  408,  408,  412,  412,  328,  327,  326,  325,
      319,  318,  317,  316,  315,  313,  312,  310,  307,  306,
      305,  304,  299,  298,  297,  296,  295,  292,  291,  290,
      288,  287,  285,  284,  283,  282,  279,  278,  277,  271,
      270,  269,  268,  264,  263,  262,  261,  259,  258,  257,
      252,  251,  250,  247,  246,  244,  239,  238,  235,  234,
      231,  230,  229,  227,  226,  224,  223,  218,  217,  213,
      212,  211,  209,  208,  206,  204,  203,  202,  200,  198,
      197,  195,  194,  192,  189,  188,  187,  185,  184,  183,

      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  110,  108,  107,  105,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   91,   90,
       88,   87,   86,   85,   83,   79,   78,   77,   76,   71,
       70,   69,   68,   66,   65,   64,   63,   62,   60,   57,

       56,   50,   49,   48,   47,   37,   36,   35,   34,   33,
       30,   29,   28,   25,   21,   20,   19,    4,    3,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[59] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 2 "flex.l"
#include <stdbool.h>
#include "y.tab.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#define STYLE 0
#define STYLEID 1
#define IS_EXPROWCOUNT 0
#define IS_EXPCOLCOUNT 1

typedef struct {
  char **array;
  size_t used;
  size_t size;
} Array;

void initialize_array(Array *a,int  size);
void free_array(Array *a);
void insert_array(Array *a, char *str);
void remove_spaces(char* source);
void yyerror (char *s);
int styleid_error=0;
Array ssid;
int counter = 1 ;
int flag;
int row_num=0;
int col_num=0;
int exprowcount_num=0;
int expcolcount_num=0;
int exprowcount_exist=0;
int expcolcount_exist=0;
int flag_2;
char * datatype;
#line 819 "lex.yy.c"

#line 821 "lex.yy.c"

#define INITIAL 0
#define comments 1
#define inside_boolean 2
#define inside_pos_int 3
#define inside_str 4
#define inside_id_str 5
#define inside_data_type 6
#define inside_data_tag 7
#define inside_data_content 8
#define comments_ins 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 58 "flex.l"


#line 1056 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 400 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 620 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 60 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("%s",src); return BEGIN_WORKBOOK;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 61 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t%s",src); return BEGIN_WORKSHEET;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 62 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t%s",src); return BEGIN_STYLES;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 63 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t%s",src); return BEGIN_STYLE;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 64 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t%s",src); return BEGIN_TABLE;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 65 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t%s",src);col_num++; return BEGIN_COLUMN; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 66 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t%s",src);row_num++; return BEGIN_ROW; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 67 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t\t%s",src); return BEGIN_CELL;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 68 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t\t\t%s",src); return BEGIN_DATA;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 69 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n%s",src); return END_WORKBOOK;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 70 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t%s",src); return END_WORKSHEET;}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 71 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t%s",src); return END_STYLES;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 72 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("%s",src); return END_STYLE;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 73 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t%s",src);

if (exprowcount_exist) {
  if (exprowcount_num != row_num) {
    fprintf(stdout, "\n\n---- ERROR FOUND. ss:ExpandedRowCount VALUE MUST AGREE WITH THE NUMBER OF ROWS ----");
    return *yytext;
  }
}
if (expcolcount_exist) {
  if (expcolcount_num != col_num) {
    fprintf(stdout, "\n\n---- ERROR FOUND. ss:ExpandedColumnCount VALUE MUST AGREE WITH THE NUMBER OF COLUMNS ----");
    return *yytext;
  }
}
row_num=0;col_num=0;exprowcount_num=0;expcolcount_num=0;exprowcount_exist=0;expcolcount_exist=0;
return END_TABLE;
}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 90 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t%s",src); return END_ROW;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 91 "flex.l"
{char* src = strdup(yytext);  remove_spaces(src);printf("\n\t\t\t\t%s",src); return END_CELL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "flex.l"
{printf("%s",yytext); return DATA;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "flex.l"
{printf("%s",yytext); return CLOSETAG;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "flex.l"
{printf("%s",yytext); return SELFCLOSINGTAG;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 95 "flex.l"
{flag = STYLE ;BEGIN(inside_id_str);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return ID_EQUALS_QUOTE;}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 97 "flex.l"
{BEGIN(inside_str);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return NAME_EQUALS_QUOTE;}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 99 "flex.l"
{BEGIN(inside_boolean);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return PROTECTED_EQUALS_QUOTE;}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 101 "flex.l"
{flag = STYLEID ; BEGIN(inside_id_str);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return STYLEID_EQUALS_QUOTE;}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 103 "flex.l"
{BEGIN(inside_boolean);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return HIDDEN_EQUALS_QUOTE;}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 105 "flex.l"
{exprowcount_exist = 1;flag_2 = IS_EXPROWCOUNT;BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return EXPANDEDROWCOUNT_EQUALS_QUOTE;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 107 "flex.l"
{expcolcount_exist = 1;flag_2 = IS_EXPCOLCOUNT; BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return EXPANDEDCOLUMNCOUNT_EQUALS_QUOTE;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 109 "flex.l"
{BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return WIDTH_EQUALS_QUOTE;}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 111 "flex.l"
{BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return HEIGHT_EQUALS_QUOTE;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 113 "flex.l"
{BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return MERGEACROSS_EQUALS_QUOTE;}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 115 "flex.l"
{BEGIN(inside_pos_int);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return MERGEDOWN_EQUALS_QUOTE;}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 117 "flex.l"
{BEGIN(inside_data_type);
char* src = strdup(yytext);  remove_spaces(src);printf(" %s",src); return TYPE_EQUALS_QUOTE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "flex.l"
{BEGIN(comments); printf("%s",yytext);
return OPEN_COMMMENTS;}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 122 "flex.l"
{
      printf("%s",yytext);
      yylval.str = strdup(yytext);
      return COMMENTS;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 127 "flex.l"
{ return *yytext; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "flex.l"
{BEGIN(INITIAL);
  printf("%s",yytext);
return CLOSE_COMMMENTS; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 132 "flex.l"
{
      if (flag == STYLE ) {
        if (counter == 1) {

          initialize_array(&ssid,strlen(strdup(yytext)));
          insert_array(&ssid,strdup(yytext));
          counter++;
        }
        else {
          int equals = 0;
          for (int i =0;i<ssid.size;i++) {
            if (!strcmp(ssid.array[i],strdup(yytext))) {
              equals = 1;
            }
          }
          if (!equals) {
            insert_array(&ssid,strdup(yytext));
          } else {
            fprintf(stdout, "\n\n---- ERROR FOUND. ss:ID VALUE MUST BE UNIQUE ----");
            free_array(&ssid);
            return *yytext;
          }
        }
      }
      else if(flag == STYLEID) {
        int equals1 = 0;
        for (int i =0;i<ssid.size;i++) {
          if (!strcmp(ssid.array[i],strdup(yytext))) {
            equals1 = 1;
          }
        }
        if (!equals1) {
          fprintf(stdout, "\n\n---- ERROR FOUND. ss:ID WITH ss:StyleID VALUE NOT FOUND ----");
          free_array(&ssid);
          return *yytext;
        }


      }
      printf("%s",yytext);
      yylval.str = strdup(yytext);
      return ID_STRING;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 175 "flex.l"
{ return *yytext; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 176 "flex.l"
{BEGIN(INITIAL);printf("%s",yytext);
return QUOTE;}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 179 "flex.l"
{
      printf("%s",yytext);
      yylval.str = strdup(yytext);
      return STRING;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 184 "flex.l"
{ return *yytext; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 185 "flex.l"
{BEGIN(INITIAL);printf("%s",yytext);
return QUOTE;  }
	YY_BREAK
case 42:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 188 "flex.l"
{
      printf("%s",yytext);
      yylval.boolean = strdup(yytext);
      return BOOLEAN;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 193 "flex.l"
{BEGIN(INITIAL);printf("%s",yytext);
return QUOTE; }
	YY_BREAK
case 44:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 196 "flex.l"
{
      if (flag_2 == IS_EXPROWCOUNT) {
        exprowcount_num = atoi(strdup(yytext));

      }
      else if (flag_2 == IS_EXPCOLCOUNT) {
        expcolcount_num = atoi(strdup(yytext));
      }

      printf("%s",yytext);
      yylval.num = atoi(strdup(yytext));
      return POSITIVE_INT;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 209 "flex.l"
{BEGIN(INITIAL);printf("%s",yytext);
return QUOTE;  }
	YY_BREAK
case 46:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 212 "flex.l"
{
      printf("%s",yytext);
      datatype = strdup(yytext);
      yylval.str = strdup(yytext);
      return DATA_TYPE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 218 "flex.l"
{BEGIN(inside_data_tag);printf("%s",yytext);
return QUOTE; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 221 "flex.l"
{ BEGIN(inside_data_content);printf("%s",yytext);
      return CLOSETAG;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 224 "flex.l"
{  return *yytext;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 227 "flex.l"
{BEGIN(comments_ins);printf("%s",yytext);
return OPEN_COMMMENTS;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 229 "flex.l"
{
      printf("%s",yytext);
      yylval.str = strdup(yytext);
      return COMMENTS;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 234 "flex.l"
{ return *yytext; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 235 "flex.l"
{BEGIN(inside_data_content);printf("%s",yytext);   return CLOSE_COMMMENTS; }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 237 "flex.l"
{
      printf("%s",yytext);
      yylval.str = strdup(yytext);
      return DATA_TEXT;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 242 "flex.l"
{BEGIN(INITIAL);printf("%s",yytext);
return ENDOPENTAG; }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 245 "flex.l"
;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 246 "flex.l"
{ return *yytext;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 248 "flex.l"
ECHO;
	YY_BREAK
#line 1600 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(comments):
			case YY_STATE_EOF(inside_boolean):
			case YY_STATE_EOF(inside_pos_int):
			case YY_STATE_EOF(inside_str):
			case YY_STATE_EOF(inside_id_str):
			case YY_STATE_EOF(inside_data_type):
			case YY_STATE_EOF(inside_data_tag):
			case YY_STATE_EOF(inside_data_content):
			case YY_STATE_EOF(comments_ins):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 400 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 400 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 399);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 248 "flex.l"

void initialize_array(Array *a,int  size) {
  a->array = malloc(sizeof(char*));
  a->used = 0;
  a->size = 1;
  a->array[a->used] = malloc((size+1) * sizeof(char));
}

void insert_array(Array *a, char *str) {
  if (a->used == a->size) {
    a->size +=1;
    a->array = realloc(a->array, a->size * sizeof(char*));
    a->array[a->used] = malloc((strlen(str)+1) * sizeof(char));
  }
    a->array[a->used++] = str;
}

void free_array(Array *a) {
  free(a->array);
  a->array = NULL;
  a->used = a->size = 0;
}

void remove_spaces(char* source)
{
  char* i = source;
  char* j = source;
  while(*j != 0)
  {
    *i = *j++;
    if(!isspace(*i))
      i++;
  }
  *i = 0;
}

